# Generated by Django 6.0.6 on 2026-06-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kitchen_station',
            field=models.CharField(blank=True, choices=[('steam', 'Steam Station'), ('grill', 'Grill Station'), ('main_kitchen', 'Main Kitchen'), ('breakfast', 'Breakfast Station'), ('beverage', 'Beverage Station'), ('dessert', 'Dessert Station')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('w', 'Waiter'), ('b', 'Billing'), ('k', 'Kitchen'), ('o', 'Owner')], default='w', max_length=2),
        ),
    ]
