# Generated by Django 6.0.6 on 2026-06-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_kitchen_station_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='sub_role',
        ),
    ]
