# Generated by Django 6.0.6 on 2026-06-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_role_user_sub_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sub_role',
            new_name='role',
        ),
    ]
