# Generated by Django 6.0.6 on 2026-06-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_kitchenstation_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name_plural': 'MenuItem'},
        ),
    ]
